version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Checking for pom.xml file"
      - if [ ! -f pom.xml ]; then
          echo "Generating pom.xml dynamically";
          echo '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.example</groupId>
                  <artifactId>example</artifactId>
                  <version>1.0-SNAPSHOT</version>
                  <dependencies></dependencies>
                </project>' > pom.xml;
        fi
      - echo "Listing files in the current directory"
      - ls -la
  build:
    commands:
      - echo "Starting Maven build"
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
